import { afterEach, describe, expect, it, jest } from '@jest/globals';
import type { AnalyticsEvent } from '@stellar-pay/types';
import {
  ConsoleAnalyticsProvider,
  NoopAnalyticsProvider,
  PostHogProvider,
  analytics,
  type AnalyticsProvider,
} from './index';

/** Records what the client hands to a provider. */
function recordingProvider(): AnalyticsProvider & {
  events: AnalyticsEvent[];
  identified: string[];
} {
  const events: AnalyticsEvent[] = [];
  const identified: string[] = [];
  return {
    name: 'recording',
    events,
    identified,
    track(event: AnalyticsEvent) {
      events.push(event);
    },
    identify(userId: string) {
      identified.push(userId);
    },
  };
}

afterEach(() => {
  // The client is a module-level singleton; put it back to the inert default.
  analytics.setProvider(new NoopAnalyticsProvider());
});

describe('AnalyticsClient', () => {
  it('starts on the noop provider, so tracking is safe before configuration', () => {
    expect(() => analytics.track('app.page_viewed')).not.toThrow();
  });

  it('forwards a tracked event to the configured provider', () => {
    const provider = recordingProvider();
    analytics.setProvider(provider);

    analytics.track('payment.succeeded', { amount: '10', assetCode: 'XLM' }, 'user-1');

    expect(provider.events).toHaveLength(1);
    const event = provider.events[0];
    expect(event.name).toBe('payment.succeeded');
    expect(event.userId).toBe('user-1');
    expect(event.properties).toEqual({ amount: '10', assetCode: 'XLM' });
    // Timestamp is generated by the client, not the caller.
    expect(Number.isNaN(Date.parse(event.timestamp))).toBe(false);
  });

  it('defaults properties to an empty object and userId to undefined', () => {
    const provider = recordingProvider();
    analytics.setProvider(provider);

    analytics.track('wallet.connected');

    expect(provider.events[0].properties).toEqual({});
    expect(provider.events[0].userId).toBeUndefined();
  });

  it('forwards identify() only when the provider implements it', () => {
    const provider = recordingProvider();
    analytics.setProvider(provider);
    analytics.identify('user-42');
    expect(provider.identified).toEqual(['user-42']);

    // A provider without identify() must not be treated as an error.
    const trackOnly: AnalyticsProvider = {
      name: 'track-only',
      track: jest.fn<(event: AnalyticsEvent) => void>(),
    };
    analytics.setProvider(trackOnly);
    expect(() => analytics.identify('user-43')).not.toThrow();
  });
});

describe('NoopAnalyticsProvider', () => {
  it('accepts events and returns nothing', () => {
    const provider = new NoopAnalyticsProvider();

    expect(provider.name).toBe('noop');
    expect(provider.track()).toBeUndefined();
  });
});

describe('ConsoleAnalyticsProvider', () => {
  it('logs the event name, properties and timestamp', () => {
    const spy = jest.spyOn(console, 'log').mockImplementation(() => {});
    const provider = new ConsoleAnalyticsProvider();

    provider.track({
      name: 'invoice.paid',
      properties: { invoiceNumber: 'INV-1' },
      timestamp: '2026-01-01T00:00:00.000Z',
    });

    expect(spy).toHaveBeenCalledWith(
      '[analytics] invoice.paid',
      { invoiceNumber: 'INV-1' },
      '2026-01-01T00:00:00.000Z',
    );
    spy.mockRestore();
  });
});

describe('PostHogProvider', () => {
  it('maps a tracked event onto posthog.capture with distinct_id', () => {
    const calls: Array<[string, Record<string, unknown> | undefined]> = [];
    const provider = new PostHogProvider({
      capture: (event, properties) => calls.push([event, properties]),
      identify: jest.fn<(userId: string) => void>(),
    });

    provider.track({
      name: 'merchant.onboarded',
      userId: 'user-9',
      properties: { merchantId: 'm-1' },
      timestamp: '2026-01-01T00:00:00.000Z',
    });

    expect(provider.name).toBe('posthog');
    expect(calls).toEqual([
      [
        'merchant.onboarded',
        {
          merchantId: 'm-1',
          distinct_id: 'user-9',
          timestamp: '2026-01-01T00:00:00.000Z',
        },
      ],
    ]);
  });

  it('delegates identify() to posthog.identify', () => {
    const identify = jest.fn<(userId: string) => void>();
    const provider = new PostHogProvider({
      capture: jest.fn<(event: string, properties?: Record<string, unknown>) => void>(),
      identify,
    });

    provider.identify('user-9');

    expect(identify).toHaveBeenCalledWith('user-9');
  });
});
